# Generated by Django 3.1.6 on 2021-02-25 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210216_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='User',
            new_name='user',
        ),
    ]
