# Generated by Django 2.2.12 on 2021-04-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinasapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(upload_to='rutinas', verbose_name='imagen post'),
        ),
    ]
