# Generated by Django 2.2.12 on 2021-04-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinasapp', '0002_auto_20210401_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.TextField(max_length=100, unique=True, verbose_name='Titulo'),
        ),
    ]
