# Generated by Django 2.2.12 on 2021-04-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinasapp', '0003_auto_20210403_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Titulo'),
        ),
    ]
